### ISSUE TITLE
证书和密码挂载报错

### ISSUE THREAD

**Issue by yizhishang** [bugfan/mytools#2]
![image](https://user-images.githubusercontent.com/12756407/59190581-a8db6900-8baf-11e9-983d-73b2f6cae826.png)

启动时，registry-srv有错误 ： level=fatal msg="open /certs/docker-registry.cert: no such file or directory"，请问下是什么原因呢

**Comment by bugfan** [comment]
你看下镜像的文档，可能是cert文件没有放对目录，也有可能没有把证书挂载导容器里面
